-- Super Kicks Seed Data
-- Run after schema.sql to populate categories and products

-- ============================================================
-- CATEGORIES
-- ============================================================
insert into public.categories (name, slug, description, image_url) values
  ('Sneakers', 'sneakers', 'Classic and modern sneakers from top brands for everyday style.', 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c25lYWtlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'),
  ('Sports', 'sports', 'High-performance sports shoes for athletes and active lifestyles.', 'https://images.unsplash.com/photo-1511886929837-354d827aae26?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8c3BvcnRzJTIwc2hvZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'),
  ('Running', 'running', 'Lightweight running shoes with responsive cushioning for every stride.', 'https://images.unsplash.com/photo-1562183241-b937e95585b6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1965&q=80'),
  ('Casual', 'casual', 'Comfortable casual shoes for everyday wear and relaxed outings.', 'https://images.unsplash.com/photo-1619216887834-a2c684de574a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80')
on conflict (name) do nothing;

-- ============================================================
-- PRODUCTS
-- ============================================================
insert into public.products (name, description, image_url, gender, color, size, category_id, price, discount_percent, discounted_price, on_sale, out_of_stock, rating_avg, rating_count, trending) values
  ('Nike Air Max 90', 'Classic sneakers with premium cushioning and style.', 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR12s55Iuvd-Wnsq0s1hmV3Ez4P4MQd6I90XvW1IE6bncbT7aC9omcKhU8CydEFt7BB-7_NiPPGTqn8kkARJD6vKUKq0EKhoAO938qN7Q7Jq-7Jt5dJA3gO8i4&usqp=CAE', 'Unisex', 'Black/White', '8', (select id from public.categories where name = 'Sneakers'), 150.00, 20, 120.00, true, false, 4.5, 0, true),
  ('Adidas Ultraboost', 'Responsive running shoes with a lightweight design.', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTFWbWBz9gaIoOirZIwvBcUbjj0vJf4dvFdCn5g6_JVbbpvA4CiXkUzUB1DfE5O55VvbR-nUsG0wQbXJZoimnjZyVH2r9sSKk9vxhqC6_-Fgrn9IjtbxIgXOQ&usqp=CAE', 'Men', 'Black', '10', (select id from public.categories where name = 'Running'), 180.00, 15, 153.00, true, false, 2.0, 0, true),
  ('Nike Air Force 1', 'Iconic sneakers with a clean and timeless design.', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSJkHTBVK0VgN3Dt5lpX53atmby1mYSe-XUV80sZFB4Kkma4TVu3eYfhyWguINJCyH76ZAJCvu8xfvkUx8rMHUQld7Wmz2cYo7p9vCXc5I99A0PEauMBJbcJOU&usqp=CAE', 'Men', 'White', '9', (select id from public.categories where name = 'Sneakers'), 100.00, 10, 90.00, true, false, 4.0, 0, true),
  ('Adidas Stan Smith', 'Classic tennis shoes with a minimalist look.', 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQcdGbzouL8QPvywx0MbSwFj7kyct_P3bL-3UyJM4BsW2lCUDADJwtQW9_3bQnb6dj7j7L5RRXiJK-p3av3vL2CYHuiCX4C3CXJptnaHEiGfCRGuJJ8vG-PLw&usqp=CAE', 'Women', 'White/Green', '7', (select id from public.categories where name = 'Casual'), 80.00, 0, 80.00, false, true, 2.0, 0, false),
  ('New Balance 990', 'Premium running shoes with excellent cushioning.', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQi1sBGJ8NFh7tBo2EiM-3A8yhuxWxHMQxckwC7haSIq4IfksV5DPT-vHG4_xCDLWA2PAtmHTSDbJLVuudXLERAfwXQlf8yxS_TkpBbS5XCOD6o-GC_lafNJQ&usqp=CAE', 'Unisex', 'Grey', '8.5', (select id from public.categories where name = 'Running'), 150.00, 25, 112.50, true, false, 0.0, 0, false),
  ('Converse Chuck Taylor All Star', 'Timeless and versatile high-top sneakers.', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQUiYdfqnj02d28CSilovRvbna249TxDTls8_aHl9M17D2UnIACR6AmbXrB_eVEHmdcOQELoB2iH0gv0seTAovPpHMeepIkgWktzb5CSVl7O9KDe-9KKXslWA&usqp=CAE', 'Unisex', 'Blue', '6', (select id from public.categories where name = 'Sneakers'), 60.00, 15, 51.00, true, false, 4.6, 0, true),
  ('Puma RS-X', 'Chunky sneakers with a retro-inspired design.', 'https://img.tatacliq.com/images/i9/437Wx649H/MP000000016286499_437Wx649H_202301300858572.jpeg', 'Men', 'White', '10.5', (select id from public.categories where name = 'Sneakers'), 120.00, 0, 120.00, false, false, 4.3, 0, true),
  ('Reebok Classic Leather', 'Timeless leather sneakers for everyday wear.', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSH1u3oSvyuIR_8SriVqyyrg4eIXaWCSQcFFBITIlqoCi1-ITlBCmLUFX_phKn97WyNt3TmUJ9qNZ301OkxKhKFiGDv_R0JpsFZKEep32ww&usqp=CAE', 'Women', 'White', '8', (select id from public.categories where name = 'Casual'), 90.00, 0, 90.00, false, true, 4.7, 0, false),
  ('Nike Zoom Pegasus 38', 'Versatile running shoes with responsive cushioning.', 'https://assets.ajio.com/medias/sys_master/root/20230306/688W/640607adaeb26924e3a755de/-473Wx593H-469431416-white-MODEL.jpg', 'Women', 'Pink/White', '7.5', (select id from public.categories where name = 'Running'), 120.00, 20, 96.00, true, false, 4.8, 0, false),
  ('Adidas Superstar V2', 'Classic sneakers with an iconic shell toe design.', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRJnq0toHlTFSVM4R4yOReOGCD5Gb857-bkjHSYl8CqSUNrTour1TQYebAaTj3W3w3Z7By97SkswbaqXTDONvendn1mKRertBsRwRYzxiIqPtVtTqqjf9ci&usqp=CAE', 'Men', 'Black/White', '9', (select id from public.categories where name = 'Sneakers'), 80.00, 10, 72.00, true, false, 4.6, 0, false),
  ('Under Armour HOVR Sonic', 'Lightweight and breathable running shoes.', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQh8dLZr2sjyM5EDRXPEycWEDY2X4oI2f1Ti8yuckz0K7hQQG1Wgo_QccKkxiD0GfY4pk0cp0av0xvAepXy1ik4Qx0kWsCkpn4lHjU_odK-k9I-00D6XyIv-g&usqp=CAE', 'Unisex', 'Black', '10', (select id from public.categories where name = 'Running'), 110.00, 0, 110.00, false, false, 1.0, 0, false),
  ('Vans Old Skool', 'Classic skateboarding shoes with a retro feel.', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQM4pqViuMJQgMLF-uOfSafI6wDW681q1Lxcx1KxQlSqYDxkqflSXdq9RcPdvAMtwerA3ULB-ZykL-4rnqitOCniRf0enVR2Z4RrfwNvlH0dFHESceFMRFP&usqp=CAE', 'Unisex', 'Black/White', '8.5', (select id from public.categories where name = 'Casual'), 70.00, 0, 70.00, false, false, 3.0, 0, false),
  ('Reebok Nano X1', 'Cross-training shoes with stability and flexibility.', 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ14s-PXFTsbECOXyN0u9_3OGIrhhupds4EX1B-VIc0XGyiBJyTVGkomfXx7ZBhVMwMohND1ALSmcdMED19cK0IlPiL3V2EER7Z_CuENDeJphxhxrHxz0uu&usqp=CAE', 'Men', 'Black/Red', '11', (select id from public.categories where name = 'Sports'), 130.00, 15, 110.50, true, false, 4.0, 0, false),
  ('Puma Suede Classic', 'Timeless suede sneakers for casual styling.', 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR7yTywd-f28I-VLZaulGh6NxZ25RqNJ6oL3_GDbCMGr4kg9HmZOCzXCPEP7YODocVDJO-fgsbkmG139K3LrGCo43A--wneG_85QQuEuPIbjXK34bYKXGDnOQ&usqp=CAE', 'Women', 'Blue', '7', (select id from public.categories where name = 'Casual'), 75.00, 0, 75.00, false, false, 3.6, 0, true),
  ('Nike Air Force 1 Low', 'The Nike Air Force 1 Low is a classic basketball shoe that has been worn by athletes and sneakerheads alike for decades. It features a durable leather upper, a comfortable cushioned midsole, and a classic rubber outsole.', 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRRx_A7EkyO5VGsXO3CkkAfKa11v3iHhauxPR4UEKyPO10Ht0JiDmQlsy5NEdUMR9nEeIPW5Dfgy6s5LecjVlze6BRo4gmKhJg9JZd93XBbdeIBwis-dVVZFQ&usqp=CAE', 'Men', 'White/Black', '9', (select id from public.categories where name = 'Sneakers'), 100.00, 20, 80.00, true, false, 4.5, 0, false),
  ('Adidas Superstar', 'The Adidas Superstar is a classic basketball shoe that was first released in 1969. It features a leather upper, a rubber shell toe, and a comfortable cushioned midsole. The Superstar is a popular choice for both athletes and sneakerheads.', 'https://img.tatacliq.com/images/i4/437Wx649H/MP000000006915880_437Wx649H_20200513230209.jpeg', 'Men', 'Black/White', '9', (select id from public.categories where name = 'Sneakers'), 120.00, 10, 110.00, true, false, 4.8, 0, true),
  ('Nike Air Jordan 1', 'The Nike Air Jordan 1 is a classic basketball shoe that was first released in 1984. It was designed for Michael Jordan and quickly became a popular choice for both athletes and sneakerheads. The Air Jordan 1 features a leather upper, a Zoom Air cushioned midsole, and a rubber outsole.', 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSOvhrbzBgxLYz98rMVBIPbGTmvV5aFibc7EHJjUf9N6lMhoSeeul0e-njTgWiv8eYeYyZM0Xo_vCLTLsPo-bEDYMPcN8sp8G2yM4Fa3V1E5kq1SS3WzKO8Ww&usqp=CAE', 'Men', 'Black/Red', '9', (select id from public.categories where name = 'Sneakers'), 200.00, 0, 200.00, false, true, 5.0, 0, true);
