import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: uuid(),
        productName: "Nike Air Max 90",
        productDescription:
            "Classic sneakers with premium cushioning and style.",
        productImage:
            "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR12s55Iuvd-Wnsq0s1hmV3Ez4P4MQd6I90XvW1IE6bncbT7aC9omcKhU8CydEFt7BB-7_NiPPGTqn8kkARJD6vKUKq0EKhoAO938qN7Q7Jq-7Jt5dJA3gO8i4&usqp=CAE",
        gender: "Unisex",
        color: "Black/White",
        size: "8",
        categoryName: "Sneakers",
        price: 150,
        discountPercent: 20,
        discountedPrice: 120,
        onSale: true,
        outOfStock: false,
        rating: 4.5,
        trending: true,
    },
    {
        _id: uuid(),
        productName: "Adidas Ultraboost",
        productDescription:
            "Responsive running shoes with a lightweight design.",
        productImage:
            "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTFWbWBz9gaIoOirZIwvBcUbjj0vJf4dvFdCn5g6_JVbbpvA4CiXkUzUB1DfE5O55VvbR-nUsG0wQbXJZoimnjZyVH2r9sSKk9vxhqC6_-Fgrn9IjtbxIgXOQ&usqp=CAE",
        gender: "Men",
        color: "Black",
        size: "10",
        categoryName: "Running",
        price: 180,
        discountPercent: 15,
        discountedPrice: 153,
        onSale: true,
        outOfStock: false,
        rating: 2,
        trending: true,
    },

    {
        _id: uuid(),
        productName: "Nike Air Force 1",
        productDescription: "Iconic sneakers with a clean and timeless design.",
        productImage:
            "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSJkHTBVK0VgN3Dt5lpX53atmby1mYSe-XUV80sZFB4Kkma4TVu3eYfhyWguINJCyH76ZAJCvu8xfvkUx8rMHUQld7Wmz2cYo7p9vCXc5I99A0PEauMBJbcJOU&usqp=CAE",
        gender: "Men",
        color: "White",
        size: "9",
        categoryName: "Sneakers",
        price: 100,
        discountPercent: 10,
        discountedPrice: 90,
        onSale: true,
        outOfStock: false,
        rating: 4,
        trending: true,
    },
    {
        _id: uuid(),
        productName: "Adidas Stan Smith",
        productDescription: "Classic tennis shoes with a minimalist look.",
        productImage:
            "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQcdGbzouL8QPvywx0MbSwFj7kyct_P3bL-3UyJM4BsW2lCUDADJwtQW9_3bQnb6dj7j7L5RRXiJK-p3av3vL2CYHuiCX4C3CXJptnaHEiGfCRGuJJ8vG-PLw&usqp=CAE",
        gender: "Women",
        color: "White/Green",
        size: "7",
        categoryName: "Casual",
        price: 80,
        discountPercent: 0,
        discountedPrice: 80,
        onSale: false,
        outOfStock: true,
        rating: 2,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "New Balance 990",
        productDescription: "Premium running shoes with excellent cushioning.",
        productImage:
            "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQi1sBGJ8NFh7tBo2EiM-3A8yhuxWxHMQxckwC7haSIq4IfksV5DPT-vHG4_xCDLWA2PAtmHTSDbJLVuudXLERAfwXQlf8yxS_TkpBbS5XCOD6o-GC_lafNJQ&usqp=CAE",
        gender: "Unisex",
        color: "Grey",
        size: "8.5",
        categoryName: "Running",
        price: 150,
        discountPercent: 25,
        discountedPrice: 112.5,
        onSale: true,
        outOfStock: false,
        rating: 0,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Converse Chuck Taylor All Star",
        productDescription: "Timeless and versatile high-top sneakers.",
        productImage:
            "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQUiYdfqnj02d28CSilovRvbna249TxDTls8_aHl9M17D2UnIACR6AmbXrB_eVEHmdcOQELoB2iH0gv0seTAovPpHMeepIkgWktzb5CSVl7O9KDe-9KKXslWA&usqp=CAE",
        gender: "Unisex",
        color: "Blue",
        size: "6",
        categoryName: "Sneakers",
        price: 60,
        discountPercent: 15,
        discountedPrice: 51,
        onSale: true,
        outOfStock: false,
        rating: 4.6,
        trending: true,
    },
    {
        _id: uuid(),
        productName: "Puma RS-X",
        productDescription: "Chunky sneakers with a retro-inspired design.",
        productImage:
            "https://img.tatacliq.com/images/i9/437Wx649H/MP000000016286499_437Wx649H_202301300858572.jpeg",
        gender: "Men",
        color: "White",
        size: "10.5",
        categoryName: "Sneakers",
        price: 120,
        discountPercent: 0,
        discountedPrice: 120,
        onSale: false,
        outOfStock: false,
        rating: 4.3,
        trending: true,
    },
    {
        _id: uuid(),
        productName: "Reebok Classic Leather",
        productDescription: "Timeless leather sneakers for everyday wear.",
        productImage:
            "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSH1u3oSvyuIR_8SriVqyyrg4eIXaWCSQcFFBITIlqoCi1-ITlBCmLUFX_phKn97WyNt3TmUJ9qNZ301OkxKhKFiGDv_R0JpsFZKEep32ww&usqp=CAE",
        gender: "Women",
        color: "White",
        size: "8",
        categoryName: "Casual",
        price: 90,
        discountPercent: 0,
        discountedPrice: 90,
        onSale: false,
        outOfStock: true,
        rating: 4.7,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Nike Zoom Pegasus 38",
        productDescription:
            "Versatile running shoes with responsive cushioning.",
        productImage:
            "https://assets.ajio.com/medias/sys_master/root/20230306/688W/640607adaeb26924e3a755de/-473Wx593H-469431416-white-MODEL.jpg",
        gender: "Women",
        color: "Pink/White",
        size: "7.5",
        categoryName: "Running",
        price: 120,
        discountPercent: 20,
        discountedPrice: 96,
        onSale: true,
        outOfStock: false,
        rating: 4.8,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Adidas Superstar V2",
        productDescription: "Classic sneakers with an iconic shell toe design.",
        productImage:
            "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRJnq0toHlTFSVM4R4yOReOGCD5Gb857-bkjHSYl8CqSUNrTour1TQYebAaTj3W3w3Z7By97SkswbaqXTDONvendn1mKRertBsRwRYzxiIqPtVtTqqjf9ci&usqp=CAE",
        gender: "Men",
        color: "Black/White",
        size: "9",
        categoryName: "Sneakers",
        price: 80,
        discountPercent: 10,
        discountedPrice: 72,
        onSale: true,
        outOfStock: false,
        rating: 4.6,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Under Armour HOVR Sonic",
        productDescription: "Lightweight and breathable running shoes.",
        productImage:
            "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQh8dLZr2sjyM5EDRXPEycWEDY2X4oI2f1Ti8yuckz0K7hQQG1Wgo_QccKkxiD0GfY4pk0cp0av0xvAepXy1ik4Qx0kWsCkpn4lHjU_odK-k9I-00D6XyIv-g&usqp=CAE",
        gender: "Unisex",
        color: "Black",
        size: "10",
        categoryName: "Running",
        price: 110,
        discountPercent: 0,
        discountedPrice: 110,
        onSale: false,
        outOfStock: false,
        rating: 1,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Vans Old Skool",
        productDescription: "Classic skateboarding shoes with a retro feel.",
        productImage:
            "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQM4pqViuMJQgMLF-uOfSafI6wDW681q1Lxcx1KxQlSqYDxkqflSXdq9RcPdvAMtwerA3ULB-ZykL-4rnqitOCniRf0enVR2Z4RrfwNvlH0dFHESceFMRFP&usqp=CAE",
        gender: "Unisex",
        color: "Black/White",
        size: "8.5",
        categoryName: "Casual",
        price: 70,
        discountPercent: 0,
        discountedPrice: 70,
        onSale: false,
        outOfStock: false,
        rating: 3,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Reebok Nano X1",
        productDescription:
            "Cross-training shoes with stability and flexibility.",
        productImage:
            "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ14s-PXFTsbECOXyN0u9_3OGIrhhupds4EX1B-VIc0XGyiBJyTVGkomfXx7ZBhVMwMohND1ALSmcdMED19cK0IlPiL3V2EER7Z_CuENDeJphxhxrHxz0uu&usqp=CAE",
        gender: "Men",
        color: "Black/Red",
        size: "11",
        categoryName: "Sports",
        price: 130,
        discountPercent: 15,
        discountedPrice: 110.5,
        onSale: true,
        outOfStock: false,
        rating: 4,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Puma Suede Classic",
        productDescription: "Timeless suede sneakers for casual styling.",
        productImage:
            "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR7yTywd-f28I-VLZaulGh6NxZ25RqNJ6oL3_GDbCMGr4kg9HmZOCzXCPEP7YODocVDJO-fgsbkmG139K3LrGCo43A--wneG_85QQuEuPIbjXK34bYKXGDnOQ&usqp=CAE",
        gender: "Women",
        color: "Blue",
        size: "7",
        categoryName: "Casual",
        price: 75,
        discountPercent: 0,
        discountedPrice: 75,
        onSale: false,
        outOfStock: false,
        rating: 3.6,
        trending: true,
    },
    {
        _id: uuid(),
        productName: "Nike Air Force 1 Low",
        productDescription:
            "The Nike Air Force 1 Low is a classic basketball shoe that has been worn by athletes and sneakerheads alike for decades. It features a durable leather upper, a comfortable cushioned midsole, and a classic rubber outsole.",
        productImage:
            "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRRx_A7EkyO5VGsXO3CkkAfKa11v3iHhauxPR4UEKyPO10Ht0JiDmQlsy5NEdUMR9nEeIPW5Dfgy6s5LecjVlze6BRo4gmKhJg9JZd93XBbdeIBwis-dVVZFQ&usqp=CAE",
        gender: "Men's",
        color: "White/Black",
        size: "9",
        categoryName: "Sneakers",
        price: "100",
        discountPercent: 20,
        discountedPrice: 80,
        onSale: true,
        outOfStock: false,
        rating: 4.5,
        trending: false,
    },
    {
        _id: uuid(),
        productName: "Adidas Superstar",
        productDescription:
            "The Adidas Superstar is a classic basketball shoe that was first released in 1969. It features a leather upper, a rubber shell toe, and a comfortable cushioned midsole. The Superstar is a popular choice for both athletes and sneakerheads.",
        productImage:
            "https://img.tatacliq.com/images/i4/437Wx649H/MP000000006915880_437Wx649H_20200513230209.jpeg",
        gender: "Men's",
        color: "Black/White",
        size: "9",
        categoryName: "Sneakers",
        price: "120",
        discountPercent: 10,
        discountedPrice: 110,
        onSale: true,
        outOfStock: false,
        rating: 4.8,
        trending: true,
    },
    {
        _id: uuid(),
        productName: "Nike Air Jordan 1",
        productDescription:
            "The Nike Air Jordan 1 is a classic basketball shoe that was first released in 1984. It was designed for Michael Jordan and quickly became a popular choice for both athletes and sneakerheads. The Air Jordan 1 features a leather upper, a Zoom Air cushioned midsole, and a rubber outsole.",
        productImage:
            "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSOvhrbzBgxLYz98rMVBIPbGTmvV5aFibc7EHJjUf9N6lMhoSeeul0e-njTgWiv8eYeYyZM0Xo_vCLTLsPo-bEDYMPcN8sp8G2yM4Fa3V1E5kq1SS3WzKO8Ww&usqp=CAE  ",
        gender: "Men's",
        color: "Black/Red",
        size: "9",
        categoryName: "Sneakers",
        price: "200",
        discountPercent: 0,
        discountedPrice: 200,
        onSale: false,
        outOfStock: true,
        rating: 5,
        trending: true,
    },
];
